"""new_auto

Revision ID: 16413da9f2f7
Revises: 506a24d3f7db
Create Date: 2022-11-28 18:21:23.322137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16413da9f2f7'
down_revision = '506a24d3f7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
