"""new_auto

Revision ID: 2272f2012ef9
Revises: abd461da046c
Create Date: 2022-11-28 17:55:57.923250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2272f2012ef9'
down_revision = 'abd461da046c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('username', sa.String(length=55), nullable=True),
    sa.Column('password', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userppp')
    op.drop_table('testooo_eng')
    op.drop_table('userooo')
    op.add_column('signup', sa.Column('nick_name', sa.String(length=33), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'nick_name')
    op.create_table('userooo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=55), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=55), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('testooo_eng',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=55), nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('userppp',
    sa.Column('userID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userNameOOO', mysql.VARCHAR(length=55), nullable=True),
    sa.Column('birthDay', sa.DATE(), nullable=True),
    sa.Column('nickName', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('test')
    # ### end Alembic commands ###
