"""new_auto

Revision ID: 506a24d3f7db
Revises: 2272f2012ef9
Create Date: 2022-11-28 18:17:56.120114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506a24d3f7db'
down_revision = '2272f2012ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
