"""enable_state

Revision ID: 87db85a5580e
Revises: f20f89c4d38d
Create Date: 2022-12-06 12:09:18.023290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87db85a5580e'
down_revision = 'f20f89c4d38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('enable_state', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'enable_state')
    # ### end Alembic commands ###
