"""enable_state

Revision ID: 9998706421fd
Revises: 87db85a5580e
Create Date: 2022-12-06 12:10:28.952668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9998706421fd'
down_revision = '87db85a5580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'nick_name')
    op.drop_column('signup', 'yes_name')
    op.drop_column('signup', 'haha_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('haha_day', mysql.DATETIME(), nullable=True))
    op.add_column('signup', sa.Column('yes_name', mysql.DATETIME(), nullable=True))
    op.add_column('signup', sa.Column('nick_name', mysql.VARCHAR(length=33), nullable=True))
    # ### end Alembic commands ###
