"""new_auto

Revision ID: e5eac8144cde
Revises: fea81b6b3477
Create Date: 2022-11-28 18:29:29.877834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5eac8144cde'
down_revision = 'fea81b6b3477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signup', 'yes_name',
               existing_type=mysql.VARCHAR(length=33),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signup', 'yes_name',
               existing_type=sa.DATETIME(),
               type_=mysql.VARCHAR(length=33),
               existing_nullable=True)
    # ### end Alembic commands ###
