"""auto_add_haha_day

Revision ID: f20f89c4d38d
Revises: 8d66ed9ddfb1
Create Date: 2022-12-01 14:33:29.642256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20f89c4d38d'
down_revision = '8d66ed9ddfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup', sa.Column('haha_day', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup', 'haha_day')
    # ### end Alembic commands ###
