"""new_auto

Revision ID: fea81b6b3477
Revises: ba0cf2a90e3a
Create Date: 2022-11-28 18:26:05.129360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea81b6b3477'
down_revision = 'ba0cf2a90e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
